### ISSUE TITLE
[CRASH] Injection warning: LVT in net/minecraft/server/players/PlayerList::m_11236_(Lnet/minecraft/server/level/ServerPlayer;Z)Lnet/minecraft/server/level/ServerPlayer; has incompatible changes at opcode 671

### ISSUE THREAD

**Issue by AqueleHaru** [Darkhax-Minecraft/Max-Health-Fix#11]
### Minecraft Version

1.20.1

### Mod Version

12.0.3

### Mod Loader

Forge

### What environment are you running the mod in?

Dedicated Server

### Issue Description

[12:29:03] [modloading-worker-0/WARN] [mixin/]: Injection warning: LVT in net/minecraft/server/players/PlayerList::m_11236_(Lnet/minecraft/server/level/ServerPlayer;Z)Lnet/minecraft/server/level/ServerPlayer; has incompatible changes at opcode 671 in callback maxhealthfix.common.mixins.json:MixinPlayerList->@Inject::onPlayerRespawn(Lnet/minecraft/server/level/ServerPlayer;ZLorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;Lnet/minecraft/core/BlockPos;FZLnet/minecraft/server/level/ServerLevel;Ljava/util/Optional;Lnet/minecraft/server/level/ServerLevel;Lnet/minecraft/server/level/ServerPlayer;)V.

### Crash Log

https://mclo.gs/mJVn3gF

### Are you doing anything weird?

Using KettingPowered on server.

**Comment by AqueleHaru** [comment]
On client-side works fine.

**Comment by Darkhax** [comment]
Hello, thank you for reporting this issue. After looking through the Ketting code for a bit, it looks like they're directly [patching](https://github.com/kettingpowered/Ketting-1-20-x/blob/1.20.4/patches/minecraft/net/minecraft/server/players/PlayerList.java.patch#L441) the games code in a way that is not safe for mod compatibility. Fixing this issue would likely require developing a version of the mod specifically for Ketting but my hands are already full with Forge/NeoForge/Fabric/Quilt support and all of the new updates Mojang has been releasing. 

The previous version 12.0.2 may have better compatibility with Ketting but that version is missing the bugfixes from 12.0.3.

**Comment by InitAuther97** [comment]
> Hello, thank you for reporting this issue. After looking through the Ketting code for a bit, it looks like they're directly [patching](https://github.com/kettingpowered/Ketting-1-20-x/blob/1.20.4/patches/minecraft/net/minecraft/server/players/PlayerList.java.patch#L441) the games code in a way that is not safe for mod compatibility. Fixing this issue would likely require developing a version of the mod specifically for Ketting but my hands are already full with Forge/NeoForge/Fabric/Quilt support and all of the new updates Mojang has been releasing.
> 
> The previous version 12.0.2 may have better compatibility with Ketting but that version is missing the bugfixes from 12.0.3.

I think using Redirect instead of Inject provides way better compatibility in this case.
Since there is only 1 invocation in that method, simply redirect the setHealth invocation, check the instance and invoke the fixed method. In this case the unused captures of local variables are not needed.
