### ISSUE TITLE
[CRASH] Before loading into the world

### ISSUE THREAD

**Issue by Niconoko** [Darkhax-Minecraft/Max-Health-Fix#13]
### Minecraft Version

1.21.1

### Mod Version

21.1.1

### Mod Loader

NeoForge

### What environment are you running the mod in?

Client

### Issue Description

Click into the existing world and crash

### Crash Log

https://pastebin.com/1ZXZsYuM

### Are you doing anything weird?

Might have installed the mods less than usual (jk), nothing in particular. (´ - ω -｀)

**Comment by VaporeonScripts** [comment]
got same bug https://mclo.gs/gRUsQmt

**Comment by wExtraBenji** [comment]
same issue

**Comment by Darkhax** [comment]
This issue has been fixed in the 21.1.3 update. The files are being processed on CurseForge and Modrinth and should be available soon.
