### ISSUE TITLE
[CRASH] crash when loading client, before the menu

### ISSUE THREAD

**Issue by antisocialian** [Darkhax-Minecraft/Max-Health-Fix#14]
### Minecraft Version

1.12.1

### Mod Version

21.1.2

### Mod Loader

NeoForge

### What environment are you running the mod in?

Client

### Issue Description

game crashes while loading, does not get to the menu.

### Crash Log

[crash-2024-10-06_09.59.06-client.txt](https://github.com/user-attachments/files/17269672/crash-2024-10-06_09.59.06-client.txt)
[debug.log](https://github.com/user-attachments/files/17269681/debug.log)
[latest.log](https://github.com/user-attachments/files/17269682/latest.log)

### Are you doing anything weird?

this pack is my own monster. i'm not dr frankenstein so it hasn't always gone well. If I disable this mod, it loads fine, but once i enable it it gives this error. my assumption is that it's a conflict or something, but i have no idea.

**Comment by Darkhax** [comment]
Hello, the crash log you provided does not point to any issues with MaxHealthFix but I do see that Better Modlist is trying to read its config file before the config has been loaded. My mod does not load until long after this stage, so there is likely a race condition or something else going on here.

**Comment by antisocialian** [comment]
that makes a lot of sense, sad i missed that :/ 

the recent update, 21.1.3 doesn't crash with both loaded, so i've got that going for me ;) thanx
