### ISSUE TITLE
[1.18.2] Collection of Singiro (compatibility)

### ISSUE THREAD

**Issue by INooBTooMuch** [Darkhax-Minecraft/Max-Health-Fix#2]
Versions :
Minecraft : 1.18.2
Max Health Fix : 1.18.2-5.0.1
Collection of Singiro : 1.18.x-1.1.2
(Its a port of Medieval Origins (Origins add on) for forge)

The "Yeti" is supposed to have extra health in all biomes except desert (some other too bc I have biome mods) and from 32 hp it has 20 in deserts but if I log in I have to regen the extra hp.

(This might be with other origins that add health idk)

**Comment by Darkhax** [comment]
Unfortunately this mod can only fix vanilla features or mods that rely directly on those features. Stuff like armor, potion effects, and enchantments. The Origins mod uses a different system to affect the max health of the player and is out of scope for this mod.
