### ISSUE TITLE
Instakill causes desyncs

### ISSUE THREAD

**Issue by Nessiesson** [Darkhax-Minecraft/Max-Health-Fix#4]
Using Forge 1.19.2-43.2.10 and MaxHealthFix-Forge-1.19.2-8.0.1.

When killing mobs with weapons strong enough to one-shot they don't actually die and instead get stuck in the dying animation client-side. And it seems like you do very little of the intended damage?

Steps to reproduce:
1. Join a world/server.
2. `/effect give @s minecraft:strength 1000000 255 true`
3. `/summon minecraft:chicken ~ ~ ~ {Health:21,Attributes:[{Name:"generic.max_health",Base:21f}]}`
4. Punch chicken.
5. Observe weirdness.

**Comment by Darkhax** [comment]
Thank you for submitting this bug. I am able to reproduce the weird issue you have described and will start working on a fix.

**Comment by Darkhax** [comment]
After looking into it for a bit I was able to find and fix the issue. An update is out for 1.20, older mc versions will get the fix soon.

**Comment by owleague** [comment]
can confirm this also happens on 1.19.2 fabric

**Comment by Darkhax** [comment]
Thanks for your patience on this, I've been in the process of moving and it was a bit more work than I expected. This should now be fixed for 1.18.2, 1.19.2, 1.19.4, 1.20, and 1.20.1.
