### ISSUE TITLE
Health Fix ignored in End Portal

### ISSUE THREAD

**Issue by SoftshoeScotty** [Darkhax-Minecraft/Max-Health-Fix#5]
Max Health Fix-Forge 1.19.2-8.0.1

Mod is ignored when jumping into End Portal. Hearts are dropped back to vanilla levels.

**Comment by Darkhax** [comment]
Thanks for letting me know about this. I think this is related but a different bug than the one fixed by this mod. I will try to fix both bugs in a future update.

**Comment by Darkhax** [comment]
This issue has finally been fixed for MC 1.20.4 with the 15.0.4 update. Older versions are getting more time consuming to maintain so I am not planning to backport this change but if there is a big enough demand I can look into it.
