### ISSUE TITLE
MaxHealthFix 8.0.1 for Minecraft 1.19.2 incorrectly shows that update is available

### ISSUE THREAD

**Issue by CatAndPaste** [Darkhax-Minecraft/Max-Health-Fix#6]
Although 8.0.1 is the latest available version for 1.19.2 on CurseForge.

![image](https://github.com/Darkhax-Minecraft/Max-Health-Fix/assets/85940028/62096dac-1dbb-4cee-be6f-cffa38fd6fed)

**Comment by Darkhax** [comment]
Hello, this is incorrect. 8.0.2 for Forge and Fabric was released July 22nd. You can find all 1.19.2 versions [here](https://www.curseforge.com/minecraft/mc-mods/max-health-fix/files?version=1.19.2)

**Comment by Maypul** [comment]
@Darkhax  It seems that 8.0.2 is not uploaded on Modrinth
![image](https://github.com/Darkhax-Minecraft/Max-Health-Fix/assets/98578889/27c2b06c-48c0-4138-b492-fc0dc1a43ade)
