### ISSUE TITLE
[Suggestion] Apply the Fix to also when respawning

### ISSUE THREAD

**Issue by Insane96** [Darkhax-Minecraft/Max-Health-Fix#7]
When you respawn the problem seems to be the same, you respawn with 20 hp instead of your max health.

**Comment by wumengzhixing** [comment]
My friend, I have the same problem, Max-Health-Fix does not work for respawning

**Comment by Darkhax** [comment]
Thanks for reporting this. This issue has finally been fixed for MC 1.20.4 with the 15.0.4 update. Older versions are getting more time consuming to maintain so I am not planning to backport this change but if there is a big enough demand I can look into it.

**Comment by wumengzhixing** [comment]
> Thanks for reporting this. This issue has finally been fixed for MC 1.20.4 with the 15.0.4 update. Older versions are getting more time consuming to maintain so I am not planning to backport this change but if there is a big enough demand I can look into it.

In 1.18.2 forge, my modpack has this fix requirement, can you consider fixing it？

**Comment by Darkhax** [comment]
@wumengzhixing Sure, I just pushed 5.0.5 for 1.18.2. The file is currently being processed by CurseForge but you can find it early for testing [here](https://maven.blamejared.com/net/darkhax/maxhealthfix/MaxHealthFix-Forge-1.18.2/5.0.5/MaxHealthFix-Forge-1.18.2-5.0.5.jar).

**Comment by wumengzhixing** [comment]
> @wumengzhixing Sure, I just pushed 5.0.5 for 1.18.2. The file is currently being processed by CurseForge but you can find it early for testing [here](https://maven.blamejared.com/net/darkhax/maxhealthfix/MaxHealthFix-Forge-1.18.2/5.0.5/MaxHealthFix-Forge-1.18.2-5.0.5.jar).

Thank you very much for making this mod.
