### ISSUE TITLE
There's a virus 

### ISSUE THREAD

**Issue by SirCroissant** [Darkhax-Minecraft/Max-Health-Fix#9]
I don't know if this is known but just in case it isn't windows defender notified me that there is a virus in the mod. I'm assuming it originated from the attack curseforge had a while back. I was using the 1.18.2 version of the mod which I know is outdated, but a lot of people use older versions so if you could find a solution it would be great!

**Comment by Darkhax** [comment]
Hey, Windows Defender has started flagging a bunch of mods as malware. This is a false positive and is affecting everyone. The file does not have a virus, and this is completely unrelated to the malware that was distributed on CurseForge last year. If you're still not sure you can scan the file using VirusTotal or a similar website. I've already submitted a ticket to Microsoft about this but have not heard back yet.
